### Test root endpoint
GET http://localhost:7007/api/v1

###

### Create Hotel
POST http://localhost:7007/api/v1/hotel
Content-Type: application/json

{
  "name": "Hotel Kammer",
  "address": "Kongens Vej 8080",
  "rooms": [
    {
    "roomNumber": 1,
      "price": 1200
    },
    {
      "roomNumber": 2,
      "price": 1500
    }
  ]
}
###

### Get all Hotels
GET http://localhost:7007/api/v1/hotel
###

### Get hotel by id
GET http://localhost:7007/api/v1/hotel/1
###

### Update hotel
PUT http://localhost:7007/api/v1/hotel/1
Content-Type: application/json

{
  "name": "Hotel Byg",
  "address": "Kongens Vej 1212",
  "rooms": [
    {
      "id": 1,
      "roomNumber": 1,
      "price": 1500
    },
    {
      "id": 2,
      "roomNumber": 2,
      "price": 2000
    }
  ]
}
### Get rooms for hotel
GET http://localhost:7007/api/v1/hotel/1/rooms
Content-Type: application/json
###

### Add room to hotel
POST http://localhost:7007/api/v1/hotel/1/rooms
Content-Type: application/json

{
"roomNumber": 3,
"price": 2500
}
###

### Remove room for hotel
DELETE http://localhost:7007/api/v1/hotel/1/rooms/2
Content-Type: application/json
###

### Delete hotel
DELETE http://localhost:7007/api/v1/hotel/1
###

